### ISSUE TITLE
Adapter trimming

### ISSUE THREAD

**Issue by sarah872** [osilander/bonito_benchmarks#2]
Cool work & post!
I see that you did not trim any adapters off by using i.e. `qcat` (I also see that in various other benchmarks). Would you explain why you think this makes/doesn't make a difference?

**Comment by osilander** [comment]
Hi, Thanks. Yes, I'm not sure adapter trimming makes much of a difference, see here: https://github.com/rrwick/Long-read-assembler-comparison/tree/96dfbe7e6edd6195cdd7fbe6f532f0022a7ebbb9#adapter-length-lower-is-better

Nevertheless you're right, I should probably try both ways...

**Comment by sarah872** [comment]
Thank you, I also have the feeling that adapter trimming makes only little difference, if any. It just confuses me because we would always do it when sequencing on Illumina
